micronaut:
  application:
    name: ${APP_NAME:dictum}
  router:
    versioning:
      enabled: true
      default-version: 1
  security:
    endpoints:
      login:
        path: '/auth/login'
      oauth:
        path: '/auth/access_token'
    authentication: bearer
    token:
      jwt:
        enabled: true
        claims-validators:
          issuer: ${micronaut.application.name}
          not-before: true
        signatures:
          secret:
            generator:
              secret: '${JWT_GENERATOR_SIGNATURE_SECRET}'
              jws-algorithm: 'HS256'
        generator:
          access-token:
            expiration: 3600
          refresh-token:
            secret: '${JWT_GENERATOR_SIGNATURE_SECRET}'
            jws-algorithm: 'HS256'
    basic-auth:
      enabled: false

mongodb:
  uri: mongodb://${MONGO_HOST:127.0.0.1}:${MONGO_PORT:27017}/${dictum.db.name}

dictum:
  api:
    version: v1
  db:
    name: ${DB_NAME:dictum}
