micronaut:
  application:
    name: dictum
  router:
    versioning:
      enabled: true
      default-version: 1
mongodb:
  uri: mongodb://${MONGO_HOST:127.0.0.1}:${MONGO_PORT:27017}

dictum:
  api:
    version: v1
  db:
    name: ${DB_NAME:dictum}