name: Publish API Docker

on:
  push:
    branches:
    - master
  pull_request:
    branches:
      - master

jobs:
  compile_and_publish:
    name: Test And Publish To Docker
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - name: Setup Java
      uses: actions/setup-java@v2
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Docker Login Docker Hub
      uses: actions-hub/docker/login@master
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
#    - name: Docker Login GitHub
#      uses: actions-hub/docker/login@master
#      env:
#        DOCKER_PASSWORD: ${{ secrets.USER_PASSWORD }}
#        DOCKER_USERNAME: ${{ secrets.USER_NAME }}
#        DOCKER_REGISTRY_URL: ghcr.io
    - name: Build with Maven
      run: mvn package